//! Rendering (and installation) of `systemd --user` units for Gezellij services.
//!
//! A service defined with `zellij service add` lives in the registry and is started on demand.
//! To have it come up at login instead, we export it as a `systemd --user` unit whose
//! `ExecStart` is `zellij service run <name>`: that command keeps the session's server as a
//! foreground child, so systemd has a real main process to track (`Type=simple`) and can apply
//! `Restart=` when the session dies unexpectedly. `ExecStop` asks the session to shut down
//! cleanly through `zellij service stop <name>`.

use super::services::ServiceDefinition;
use std::fs;
use std::io;
use std::path::{Path, PathBuf};

/// The systemd unit name for a service (`gezellij-<name>.service`).
pub fn unit_name(service_name: &str) -> String {
    format!("gezellij-{}.service", service_name)
}

/// Where `systemd --user` units belonging to this user live.
pub fn user_unit_dir() -> Option<PathBuf> {
    if let Some(xdg_config_home) = std::env::var_os("XDG_CONFIG_HOME") {
        if !xdg_config_home.is_empty() {
            return Some(PathBuf::from(xdg_config_home).join("systemd").join("user"));
        }
    }
    std::env::var_os("HOME").map(|home| {
        PathBuf::from(home)
            .join(".config")
            .join("systemd")
            .join("user")
    })
}

/// Quote a value the way systemd expects it inside a unit file: bare when it is a simple word,
/// double-quoted (with `\` and `"` escaped) otherwise.
fn quote(value: &str) -> String {
    let needs_quoting = value.is_empty()
        || value
            .chars()
            .any(|c| c.is_whitespace() || matches!(c, '"' | '\'' | '\\' | '$' | ';' | '%' | '#'));
    if !needs_quoting {
        return value.to_string();
    }
    let mut quoted = String::with_capacity(value.len() + 2);
    quoted.push('"');
    for c in value.chars() {
        if c == '\\' || c == '"' {
            quoted.push('\\');
        }
        quoted.push(c);
    }
    quoted.push('"');
    quoted
}

/// `Environment=` assignments are always double-quoted (systemd splits unquoted ones on
/// whitespace), so this escapes rather than deciding whether quoting is needed.
fn quote_always(value: &str) -> String {
    let mut quoted = String::with_capacity(value.len() + 2);
    quoted.push('"');
    for c in value.chars() {
        if c == '\\' || c == '"' {
            quoted.push('\\');
        }
        quoted.push(c);
    }
    quoted.push('"');
    quoted
}

/// Render a complete `systemd --user` unit for `service`.
///
/// `executable` is the `zellij`/`gezellij` binary the unit should call back into, and `extra_env`
/// is a list of `(KEY, VALUE)` pairs turned into `Environment=` lines (useful to pin the socket or
/// config directory the unit should use).
pub fn render_user_unit(
    service: &ServiceDefinition,
    executable: &Path,
    extra_env: &[(String, String)],
) -> String {
    let executable = quote(&executable.to_string_lossy());
    let mut unit = String::new();
    unit.push_str("# Generated by `zellij service export-systemd`.\n");
    unit.push_str(
        "# `service run` keeps the session server in the foreground so systemd can track it.\n",
    );
    unit.push_str("[Unit]\n");
    unit.push_str(&format!("Description=Gezellij service: {}\n", service.name));
    // No `After=default.target`: a target implicitly orders itself After= everything it Wants=,
    // so combining that with `WantedBy=default.target` would create an ordering cycle.
    unit.push('\n');
    unit.push_str("[Service]\n");
    unit.push_str("Type=simple\n");
    unit.push_str("Restart=on-failure\n");
    unit.push_str("RestartSec=2\n");
    if let Some(cwd) = service.cwd.as_ref() {
        unit.push_str(&format!(
            "WorkingDirectory={}\n",
            quote(&cwd.to_string_lossy())
        ));
    }
    for (key, value) in extra_env {
        unit.push_str(&format!(
            "Environment={}\n",
            quote_always(&format!("{}={}", key, value))
        ));
    }
    unit.push_str(&format!(
        "ExecStart={} service run {}\n",
        executable, service.name
    ));
    unit.push_str(&format!(
        "ExecStop={} service stop {}\n",
        executable, service.name
    ));
    unit.push('\n');
    unit.push_str("[Install]\n");
    unit.push_str("WantedBy=default.target\n");
    unit
}

/// Write the unit for `service` into the user unit directory, returning the file it was written to.
pub fn install_user_unit(
    service: &ServiceDefinition,
    executable: &Path,
    extra_env: &[(String, String)],
) -> io::Result<PathBuf> {
    let dir = user_unit_dir().ok_or_else(|| {
        io::Error::new(
            io::ErrorKind::NotFound,
            "could not determine the systemd user unit directory (neither XDG_CONFIG_HOME nor HOME is set)",
        )
    })?;
    fs::create_dir_all(&dir)?;
    let path = dir.join(unit_name(&service.name));
    fs::write(&path, render_user_unit(service, executable, extra_env))?;
    Ok(path)
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::input::command::RestartPolicy;

    #[test]
    fn unit_name_is_prefixed() {
        assert_eq!(unit_name("api"), "gezellij-api.service");
        assert_eq!(unit_name("my-bot_2.0"), "gezellij-my-bot_2.0.service");
    }

    #[test]
    fn renders_without_cwd() {
        let service = ServiceDefinition::new(
            "api",
            vec!["./start.sh".into()],
            None,
            RestartPolicy::OnFailure,
        );
        let unit = render_user_unit(&service, Path::new("/usr/bin/zellij"), &[]);
        assert!(unit.starts_with("# Generated by `zellij service export-systemd`."));
        assert!(unit.contains("Description=Gezellij service: api\n"));
        assert!(!unit.contains("After="));
        assert!(unit.contains("Type=simple\nRestart=on-failure\nRestartSec=2\n"));
        assert!(!unit.contains("WorkingDirectory="));
        assert!(!unit.contains("Environment="));
        assert!(unit.contains("ExecStart=/usr/bin/zellij service run api\n"));
        assert!(unit.contains("ExecStop=/usr/bin/zellij service stop api\n"));
        assert!(unit.ends_with("[Install]\nWantedBy=default.target\n"));
    }

    #[test]
    fn renders_with_cwd_and_environment() {
        let service = ServiceDefinition::new(
            "api",
            vec!["./start.sh".into()],
            Some(PathBuf::from("/srv/api")),
            RestartPolicy::Always,
        );
        let env = vec![(
            "ZELLIJ_CONFIG_DIR".to_string(),
            "/home/me/.config/zellij".to_string(),
        )];
        let unit = render_user_unit(&service, Path::new("/usr/bin/zellij"), &env);
        assert!(unit.contains("WorkingDirectory=/srv/api\n"));
        assert!(unit.contains("Environment=\"ZELLIJ_CONFIG_DIR=/home/me/.config/zellij\"\n"));
    }

    #[test]
    fn quotes_paths_containing_spaces() {
        let service = ServiceDefinition::new(
            "api",
            vec!["./start.sh".into()],
            Some(PathBuf::from("/srv/my app")),
            RestartPolicy::No,
        );
        let unit = render_user_unit(
            &service,
            Path::new("/opt/my tools/zellij"),
            &[("A B".to_string(), "c\"d".to_string())],
        );
        assert!(unit.contains("WorkingDirectory=\"/srv/my app\"\n"));
        assert!(unit.contains("ExecStart=\"/opt/my tools/zellij\" service run api\n"));
        assert!(unit.contains("ExecStop=\"/opt/my tools/zellij\" service stop api\n"));
        assert!(unit.contains("Environment=\"A B=c\\\"d\"\n"));
    }

    #[test]
    fn quoting_leaves_simple_values_alone() {
        assert_eq!(quote("/usr/bin/zellij"), "/usr/bin/zellij");
        assert_eq!(quote("simple-value_1.0"), "simple-value_1.0");
        assert_eq!(quote(""), "\"\"");
        assert_eq!(quote("back\\slash"), "\"back\\\\slash\"");
    }
}
